name: CI
on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: Install deps
        run: npm ci
      - name: Lint (skip if no config)
        run: |
          if [ -f eslint.config.js ]; then npm run lint || echo "Lint warnings"; fi
      - name: Build
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
        run: |
          : "Fail if envs missing" 
          test -n "${VITE_SUPABASE_URL}" || { echo 'Missing VITE_SUPABASE_URL'; exit 1; }
          test -n "${VITE_SUPABASE_ANON_KEY}" || { echo 'Missing VITE_SUPABASE_ANON_KEY'; exit 1; }
          npm run build
      - name: Smoke Script
        run: |
          if [ -f scripts/smokeCheck.mjs ]; then node scripts/smokeCheck.mjs || true; fi
      - name: Summary
        run: echo "CI pipeline completed successfully"
